secure.CheckPrinting.com/Models/Check.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace secure.CheckPrinting.com.Models
{
    public class Check
    {
       public List<CheckElements> CheckElementsList { get; set; }
    }

    public class CheckElements
    {
        public string Name { get; set; }
        public int Top { get; set; }
        public int Left { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }

}

secure.CheckPrinting.com/Controllers/CheckController.cs
using secure.CheckPrinting.com.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace secure.CheckPrinting.com.Controllers
{
    public class CheckController : Controller
    {
        #region Index
        // GET: Check
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region Add New Check Templete
        /// <summary>
        /// Add New Check Templete
        /// </summary>
        /// <returns></returns>
        public ActionResult AddNewCheckTemplete(long? id)
        {
            return View();
        }
        #endregion

        #region Save Check Template
        /// <summary>
        /// Save Check Template
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SaveCheckTemplate(List<CheckElements> CheckElementsList)
        {
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

secure.CheckPrinting.com/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace secure.CheckPrinting.com.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

secure.CheckPrinting.com/Views/Check/AddNewCheckTemplete.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
    @using (Html.BeginForm("SaveCheckTemplate", "Check", FormMethod.Get, new { id = "frmSaveCheckTemplate", autocomplete = "off" }))
    {
        <div style="border: 1px solid rgba(0, 0, 0, 0.2); margin-bottom: 15px; margin-top: 50px;  padding: 15px 15px 0px;">
            <div class="check">
                <div id="logo" data-item-name="BUSINESSLOGO" class="ui-widget-content">
                    <p>logo</p>
                </div>
                <div id="BusinessName" data-item-name="BUSINESSNAME" class="ui-widget-content">
                    <span>Business Name</span>
                </div>
            </div>
        </div>
        <div class="spacer15"></div>
        <div>
            <input type="button" value="Save" id="btnSaveCheck" onclick="SaveCheckTemplate(this);" />
        </div>
    }
</body>
</html>

<script type="text/javascript">
    $(function () {
        $("#logo").draggable({ containment: "parent" });
        $("#BusinessName").draggable({ containment: "parent" });
    });

    function SaveCheckTemplate(obj) {
        if ($("#frmSaveCheckTemplate").valid()) {
            $(obj).attr('disabled', true);
            var checkElementsList = [];
            var i = 0;
            $("div[class*='ui-widget-content']").each(function () {
                var element = {};
                element['Name'] = $(this).attr('data-item-name');
                element['Top'] = $(this).css('left').replace('px', '');
                element['Left'] = $(this).css('top').replace('px', '');
                element['Width'] = $(this).css('width').replace('px', '');
                element['Height'] = $(this).css('height').replace('px', '');
                checkElementsList[i] = element;
                i++;
            });
            $.ajax({
                type: "POST",
                url: "/Check/SaveCheckTemplate",
                data: {
                    CheckElementsList: checkElementsList
                },
                async: true,
                success: function (data) {
                    if (data != null && data.Status == 'Success') {
                        $(obj).attr('disabled', false);
                    } else {
                        $(obj).attr('disabled', false);
                    }
                }
            });
        }
    }

</script>

secure.CheckPrinting.com/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

secure.CheckPrinting.com/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

secure.CheckPrinting.com/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

secure.CheckPrinting.com/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>